const assert=require('node:assert/strict');
const {courseTrust,freshness,taskStatus}=require('../web/workbench-insights.js');
const unknown=courseTrust({year:'2026',schedule:{raw:'',sessions:[]}}, {modifiedAt:999999});
assert.match(unknown.term,/未提供/);assert.equal(unknown.queriedAt,'未记录');assert.equal(unknown.schedule,'缺失');
assert.equal(courseTrust({schedule:{sessions:[{}],teachingKnown:false}}).schedule,'部分识别');
assert.equal(courseTrust({schedule:{raw:'待定',sessions:[]}}).schedule,'未识别');
assert.equal(courseTrust({schedule:{teachingKnown:true}}).schedule,'已识别');
const known=courseTrust({rawRows:[{'学期':'2026秋','查询时间':'2026-09-07T08:00:00+08:00'}]});
assert.equal(known.term,'2026秋');assert.ok(Number.isFinite(known.timestamp));
assert.match(freshness(1000,90000),/超过 24/);assert.match(freshness(null),/未记录/);assert.match(freshness(1000,0),/异常/);
const task=(code,active=true,phase='running')=>({state:{active,phase,courses:[{reasonCode:code}]}});
assert.match(taskStatus(task('pending_confirmation')).title,/待复核/);
assert.match(taskStatus(task('no_seats')).title,/等待空位/);
assert.match(taskStatus(task('school_notice')).action,/原始提示/);
assert.match(taskStatus(task('confirmed',false,'stopped')).action,/历史/);
assert.match(taskStatus(task('mutex',false,'completed')).action,/不等于选上/);
assert.match(taskStatus({...task('no_seats'),nextPollAt:5},10).next,/可能/);
assert.match(taskStatus({state:{active:false,phase:'error',outcome:{code:'network_error',message:'timeout'}}}).title,/需要处理/);
assert.equal(taskStatus({state:{active:true,phase:'running',outcome:{code:'network_error'},courses:[{reasonCode:'confirmed'}]}}).code,'network_error');
console.log('Workbench insight checks passed: provenance, unknowns, stale data, pending results and task state.');
